// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJLBOfNXFWgvm9Fq7anBGz5rr7o7NCW5Q',
    appId: '1:861104631232:android:7d9b31f998df0051cbac25',
    messagingSenderId: '861104631232',
    projectId: 'lung-life',
    storageBucket: 'lung-life.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCltjaGCvHQC61XIDTJJIzfue2CloWEHDQ',
    appId: '1:861104631232:ios:aecd0f5174a8292bcbac25',
    messagingSenderId: '861104631232',
    projectId: 'lung-life',
    storageBucket: 'lung-life.firebasestorage.app',
    iosBundleId: 'com.example.ahmed11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKs09wg_fY4BP3OSS7w57B_3mKEhuUZ3U',
    appId: '1:861104631232:web:1894664845653cefcbac25',
    messagingSenderId: '861104631232',
    projectId: 'lung-life',
    authDomain: 'lung-life.firebaseapp.com',
    storageBucket: 'lung-life.firebasestorage.app',
    measurementId: 'G-B4MEGFDSJE',
  );
}
